language: go

go:
  - 1.4
  - tip

sudo: false

install: 
  - go get -t -d -v ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/golang/lint/golint

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
  - golint ./...

notifications:
  webhooks:
    urls: 
      - https://webhooks.gitter.im/e/9caacfa1bede5e900019
    on_success: change
